apiVersion: v1
kind: Service
metadata:
  name: {{ include "library-server-chart.fullname" . }}
  labels:
    {{- include "library-server-chart.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "2112"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "library-server-chart.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: 2112
      protocol: TCP
